// src/app/components/charity/charity.component.ts
import { Component, OnInit } from '@angular/core';
import { faFacebook } from '@fortawesome/free-brands-svg-icons';

@Component({
  selector: 'app-charity',
  templateUrl: './charity.component.html',
  styleUrls: ['./charity.component.css']
})
export class CharityComponent implements OnInit {
  faFacebook = faFacebook;

  constructor() { }

  ngOnInit(): void {
  }

  donateFacebook() {
    window.open('https://www.facebook.com/donate/5194665980557244/?fundraiser_source=https://www.zeldathon.co.uk/', '_blank');
  }

  donateJustGiving() {
    window.open('https://www.justgiving.com/fundraising/zeldathonuk-gameblast2022', '_blank');
  }

}

<div class="container p-3 min-vh-100 text-white text-center">
  <div class="my-3">

    <div class="mb-5">
      <h1 class="golden-text text-uppercase">Who are we fundraising for?</h1>
    </div>

    <div class="">

      <div class="d-flex justify-content-center p-3">
        <div class="">
          <a href="https://www.specialeffect.org.uk/" target="_blank">
            <img class="w-75"
                 src="../../../assets/img/SE_Logo_Proud_To_Support_White.png" alt="SpecialEffect Logo">
          </a>
        </div>
      </div>

      <div class="d-flex justify-content-center my-5">
        <div class="w-75" style="font-size: 1.25em;">
          <a class="text-info" href="https://www.specialeffect.org.uk/" target="_blank">SpecialEffect</a> want everyone to be included.
          That’s why they’re transforming the lives of physically disabled people right across the world through the innovative use of technology.
          At the heart of their work is a mission to maximise fun and quality of life by helping people control video games to the best of their abilities,
          but that’s just the start.
        </div>
      </div>

      <div class="embed-responsive-16by9 my-5">
        <iframe class="w-75" height="470" src="https://www.youtube-nocookie.com/embed/videoseries?list=PLHsLVX3Ok858h4N9ca2SuQjhqDJQga_cg" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>

      <div class="d-flex justify-content-center my-5">
        <div class="w-75">
          <a class="btn btn-lg btn-outline-info text-uppercase me-5" style="font-size: 2em;" href="https://www.specialeffect.org.uk/what-we-do/our-work" target="_blank">Can They Help?</a>
        </div>
      </div>

      <div class="d-flex justify-content-center my-5">
        <div class="d-flex justify-content-around w-75">
          <button class="btn btn-sm btn-facebook p-3" (click)="donateFacebook();" style="font-family: 'Bungee', cursive; font-size: 2em;">
            <div class="d-flex text-white" title="Donate via Facebook!">
              <div class="d-flex align-self-center" style="width: .9em;">
                <fa-icon [icon]="faFacebook" style="position: relative; top: 2px;"></fa-icon>
              </div>
              <span style="position: relative; top: 2px;">&nbsp;Donate</span>
            </div>
          </button>
          <button class="btn btn-sm btn-justgiving p-3" (click)="donateJustGiving();" style="font-family: 'Bungee', cursive; font-size: 2em;">
            <div class="d-flex text-white" title="Donate via JustGiving!">
              <div class="d-flex align-self-center" style="width: .9em;">
                <img style="max-width: .9em; filter: brightness(10);"
                     src="../../../assets/img/justgiving-g.svg" alt="JustGiving logo">
              </div>
              <span style="position: relative; top: 1px;">&nbsp;Donate</span>
            </div>
          </button>
        </div>
      </div>

    </div>

  </div>
</div>

// frontend/src/routes/Charity.tsx
import { DonationCards } from '@/components/DonationCards';
import './charity.css';

const SPECIALEFFECT_LEARN = 'https://www.specialeffect.org.uk/what-we-do/our-work';

export function Charity() {
  return (
    <div className="container p-3 min-vh-100 text-white text-center">
      <div className="my-3">
        <div className="mb-5">
          <h1 className="text-bloodmoon text-uppercase">Who are we fundraising for?</h1>
        </div>

        <div>
          <div className="d-flex justify-content-center p-3">
            <a href="https://www.specialeffect.org.uk/" target="_blank" rel="noreferrer">
              <img
                className="w-50"
                src="/assets/img/SE_Logo_Proud_To_Support_White.png"
                alt="SpecialEffect Logo"
              />
            </a>
          </div>

          <div className="d-flex justify-content-center my-5">
            <div className="w-75" style={{ fontSize: '1.25em' }}>
              <a
                className="text-info"
                href="https://www.specialeffect.org.uk/"
                target="_blank"
                rel="noreferrer"
              >
                SpecialEffect
              </a>{' '}
              want everyone to be included. That's why they're transforming the lives
              of physically disabled people right across the world through the
              innovative use of technology. At the heart of their work is a mission to
              maximise fun and quality of life by helping people control video games to
              the best of their abilities, but that's just the start.
            </div>
          </div>

          <div className="embed-responsive-16by9 my-5">
            <iframe
              className="w-75"
              height="470"
              title="SpecialEffect videos"
              src="https://www.youtube-nocookie.com/embed/videoseries?list=PLHsLVX3Ok858h4N9ca2SuQjhqDJQga_cg"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            />
          </div>

          <div className="d-flex justify-content-center my-5">
            <div className="w-75">
              <a
                className="btn btn-lg btn-specialeffect text-uppercase me-5"
                style={{ fontSize: '2em' }}
                href={SPECIALEFFECT_LEARN}
                target="_blank"
                rel="noreferrer"
              >
                Can They Help You?
              </a>
            </div>
          </div>

          <div className="my-5">
            <div className="d-flex justify-content-start">
              <h6 className="text-bloodmoon">Make a donation</h6>
            </div>
            <DonationCards />
          </div>
        </div>
      </div>
    </div>
  );
}
