// src/app/components/donations/donations.component.ts
import {Component, OnInit} from '@angular/core';
import TimeAgo from 'javascript-time-ago';
import en from 'javascript-time-ago/locale/en';
import {Observable} from 'rxjs';
import {DonationTrackingService} from '../../services/firebase/donation-tracking/donation-tracking.service';
import {TrackedDonationId} from '../../services/firebase/donation-tracking/tracked-donation';


/**
 * COMPONENT IS DISPLAYED WITHIN THE DONATIONS PAGE
 */
@Component({
  selector: 'app-donations',
  templateUrl: './donations.component.html',
  styleUrls: ['./donations.component.css']
})
export class DonationsComponent implements OnInit {
  public timeAgo: TimeAgo;
  public trackedDonationIds$: Observable<TrackedDonationId[]>;

  constructor( private donationTrackingService: DonationTrackingService ) {
  }

  ngOnInit() {
    TimeAgo.addLocale(en);
    this.timeAgo = new TimeAgo('en-GB');
    this.trackedDonationIds$ = this.donationTrackingService.getTrackedDonationId();
  }

  donateFacebook() {
    window.open('https://www.facebook.com/donate/655011391974449/?fundraiser_source=https://www.zeldathon.co.uk/', '_blank');
  }

  donateJustGiving() {
    window.open('https://www.justgiving.com/fundraising/zeldathonuk-gameblast-2020', '_blank');
  }

  getDateFromJustGivingString(dateStr: string): Date {
    const date1 = parseInt(dateStr.substring(6, dateStr.length - 7), 0);
    return new Date(date1);
  }

}

<div class="d-flex flex-row min-vh-100">

  <div class="p-3 d-none d-xl-block">
    <div class="d-flex flex-column">

      <div class="text-center card bg-dark d-inline-block position-sticky mb-3" style="width: 22rem;">
        <div class="text-center card card-header bg-dark text-light">
          <h5 class="card-title mb-0">Who are we fundraising for?</h5>
        </div>
        <div class="card-body">
          <div class="embed-responsive-16by9">
            <iframe src="https://www.youtube-nocookie.com/embed/videoseries?list=PLHsLVX3Ok858h4N9ca2SuQjhqDJQga_cg" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="d-flex justify-content-center p-3">
            <a href="https://www.specialeffect.org.uk/" target="_blank">
              <img style="max-height: 50px;"
                   src="../../../assets/img/logo-specialeffect.png"
                   alt="SpecialEffect Logo"></a>
          </div>
          <div class="text-light" style="font-size: 0.7em;">
            <a class="text-info" href="https://www.specialeffect.org.uk/" target="_blank">SpecialEffect</a> are a charity putting fun and inclusion
            back into the lives of people with physical disabilities
            by helping them play video games to the very best
            of their abilities. They match or modify technology to
            create and truly personalised gaming control setups,
            and back this up with lifelong support. They’re also
            working with developers to help make gaming as
            accessible as possible to everyone around the world.
          </div>
        </div>
        <div class="card-footer">
          <div class="d-flex justify-content-around">
            <button class="btn btn-sm btnfacebook mr-3" (click)="donateFacebook();">
              Donate via Facebook<br/>
              <span class="small text-white-50">*no fees</span>
            </button>
            <button class="btn btn-sm btn-justgiving" (click)="donateJustGiving();">
              Donate via JustGiving<br/>
              <span class="small text-warning">*adds fees to donation!</span>
            </button>
          </div>
        </div>
      </div>

      <div class="card bg-dark mb-2" style="width: 22rem;">
        <div class="card-header d-inline-block position-sticky">
          <div class="d-flex flex-column">
            <span class="text-white-50" style="font-size: 0.8em;">Facebook Fundraisers Page:</span>
            <a class="text-light text-break" style="font-size: 0.8em;" href="https://www.facebook.com/donate/855003971855785/" target="_blank">https://www.facebook.com/donate/855003971855785/</a>
          </div>
        </div>
      </div>
      <div class="card bg-dark" style="width: 22rem;">
        <div class="card-header d-inline-block position-sticky">
          <div class="d-flex flex-column">
            <span class="text-white-50" style="font-size: 0.8em;">JustGiving Page:</span>
            <a class="text-light text-break" style="font-size: 0.8em;" href="https://www.justgiving.com/fundraising/zeldathonuk-gameblast2022" target="_blank">https://www.justgiving.com/fundraising/zeldathonuk-gameblast2022</a>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="container donation-list-container p-3">

    <div class="">
      <h3 class="text-white mb-3">Thank you to all our donors!</h3>
      <p class="text-light">
        On behalf of everyone in the ZeldathonUK team we would like to thank all of the donors below for their generous donations:
      </p>

      <!--
      <pre>
        {{ (fundraisingPageDonations | async) | json }}
      </pre>
      -->

      <ng-container *ngIf="(trackedDonationIds$ | async) as tds">

        <ng-template [ngIf]="tds.length >= 1">
          <div class="card-columns min-vh-100">
            <div class="card donor-list mb-2" *ngFor="let donation of tds">

              <div class="d-flex flex-column donation" [ngClass]="donation.donationSource === 'Facebook' ? 'facebook-donation' : 'justgiving-donation'">

                <div class="d-flex justify-content-between">
                  <div class="d-flex justify-content-start">
                    <div class="d-flex align-self-center">
                      <img class="donation-img"
                           [src]="donation.imgUrl"
                           [alt]="donation.name"
                           [title]="donation.name">
                    </div>
                    <div class="d-flex align-self-start ml-2">
                      <h5 class="mb-0" style="word-break: break-word;">{{ donation.name }}</h5>
                    </div>
                  </div>
                </div>

                <div class="my-2 small" *ngIf="donation.message.length >= 1">
                  <span class="position-relative" style="font-size: 2em; font-family: 'Poppins', sans-serif; top: 0.2em;">&ldquo;</span>
                  <i class="px-1" style="font-size: 1.2em; font-family: 'Poppins', sans-serif;">{{ donation.message.length >= 1 ? donation.message : '-' }}</i>
                  <span class="position-relative" style="font-size: 2em; font-family: 'Poppins', sans-serif; top: 0.7em;">&rdquo;</span>
                </div>

                <div class="d-flex justify-content-between">
                  <div class="d-flex align-self-end">
                    <div class="badge badge-pill badge-success" *ngIf="donation.giftAidAmount">
                      <a href="https://www.gov.uk/donating-to-charity/gift-aid" target="_blank" class="text-white"
                         title="Gift Aid declaration made for the charity to claim additional 25% of donation">GiftAid</a>: {{ donation.giftAidAmount | currency:donation.currency }}
                    </div>
                  </div>
                  <div class="">
                    <h3 class="mb-0">{{ donation.donationAmount | currency:donation.currency }}</h3>
                  </div>
                </div>

                <div class="d-flex justify-content-end">
                  <span class="text-white-50" style="font-size: 9px;">{{ timeAgo.format(donation.donationDate.toDate()) }}</span>
                </div>

              </div>

            </div>
          </div>
        </ng-template>

        <ng-template [ngIf]="tds.length === 0">
          <div class="d-flex justify-content-center h-75">
            <div class="d-flex align-self-center">
              <div class="d-flex flex-column">
              <h6 class="text-white-50 mb-3">
                No donors yet! Please consider starting us off!
              </h6>
              <div class="d-flex justify-content-around">
                <div class="d-flex flex-column">
                  <button class="btn btn-lg btnfacebook mr-3" (click)="donateFacebook();">
                    Donate via Facebook<br/>
                    <span class="small text-white-50">*no fees</span>
                  </button>
                </div>
                <div class="d-flex flex-column">
                  <button class="btn btn-lg btn-justgiving" (click)="donateJustGiving();">
                    Donate via JustGiving<br/>
                    <span class="small text-warning">*adds fees to donation!</span>
                  </button>
                </div>
              </div>
              </div>
            </div>
          </div>
        </ng-template>

      </ng-container>
    </div>

  </div>

  <div class="p-3 d-none d-xl-block">
    <div class="card bg-dark" style="width: 22rem;">
      <div class="text-center card card-header bg-dark text-light">
        <h5 class="card-title mb-0">What will your donation do?</h5>
      </div>
      <div class="text-center card card-body bg-dark small">
        <div class="text-light mb-3">
          All of <a class="text-info" href="https://www.specialeffect.org.uk/" target="_blank">SpecialEffect</a>'s services are provided <span class="text-warning">free of charge</span>, so they rely entirely on your generosity to keep on transforming lives.
        </div>
        <table class="table table-hover table-striped table-dark small mb-0">
          <tbody>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;5
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="https://static.dezeen.com/uploads/2018/05/xbox-controller-technology-games-design_dezeen_2364_col_23.jpg"
                   alt="Flexible Fixings">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Can buy flexible fixings to enable a correct and firm hold of controller, joystick or button for safe and comfortable use.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;10
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="https://hedaroart.files.wordpress.com/2016/05/infinity4ps-thumbstick-heights.jpg?w=428&h=161"
                   alt="Joystick Extensions">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Could purchase joystick extensions, to potentially enable greater control of a thumbstick, with its increased leverage.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;25
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="https://www.specialeffect.org.uk/images/sasha_1000.jpg"
                   alt="Deliver Adaptive Gaming Setup">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Will enable us to deliver an adapted gaming setup quickly and directly to someone who needs it.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;50
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="http://permobilus.com/wp-content/uploads/2016/11/2_ALT_MiniJoystick-min.jpg"
                   alt="Low Force Joysticks">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Will buy a gamepad to be modified in the workshop with low force joysticks and buttons for a gamer with weak hand muscles to use.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;75
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="https://compass-ssl.xbox.com/assets/3f/2c/3f2cd0bf-3b0e-402d-9c59-a8fdbd73ff47.png?n=Xbox-Accessibility_Image-0_Adaptive-Controller_1600x658.png"
                   alt="Xbox Adaptive Controller">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Will buy an interface box like an
                <a class="text-info" href="https://www.xbox.com/en-GB/accessories/controllers/xbox-adaptive-controller" target="_blank">Xbox Adaptive Controller</a>
                for use as part of a gaming setup.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;100
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="https://i1.wp.com/meru.org.uk/wp-content/uploads/2019/08/mounted-to-chair-in-use.jpg?fit=1184%2C888&ssl=1"
                   alt="Mounting System">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Can enable us to buy a mounting system which will hold a joystick and position it for optimum use by a gamer to control it.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;200
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="https://www.evilcontrollers.com/media/pages/gaming/img_01.jpg"
                   alt="Single Handed Controller">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Could buy a single handed controller to enable a disabled gamer to play with just one hand.</span>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>

// frontend/src/routes/Donations.tsx
import { Link } from 'react-router';
import { DonationCards } from '@/components/DonationCards';
import './donations.css';

/**
 * Real donor data was sourced from Firebase. Until the Django backend is
 * wired up the donor list is empty and the page renders the legacy
 * "empty state" view (donate-cards + SpecialEffect benefits sidebar).
 */
const trackedDonations: unknown[] = [];

const benefitRows = [
  {
    amount: '£5',
    img: '/assets/img/donation-items/xbox-controller-technology-games-design_dezeen_2364_col_23_1_-removebg-preview.png',
    alt: 'Flexible Fixings',
    desc: 'Can buy flexible fixings to enable a correct and firm hold of controller, joystick or button for safe and comfortable use.',
  },
  {
    amount: '£10',
    img: '/assets/img/donation-items/infinity4ps-thumbstick-heights-removebg-preview.png',
    alt: 'Joystick Extensions',
    desc: 'Could purchase joystick extensions, to potentially enable greater control of a thumbstick, with its increased leverage.',
  },
  {
    amount: '£25',
    img: '/assets/img/donation-items/sasha_setup-e1628153142123-removebg-preview.png',
    alt: 'Deliver Adaptive Gaming Setup',
    desc: 'Will enable us to deliver an adapted gaming setup quickly and directly to someone who needs it.',
  },
  {
    amount: '£50',
    img: '/assets/img/donation-items/2_ALT_MiniJoystick-min-removebg-preview.png',
    alt: 'Low Force Joysticks',
    desc: 'Will buy a gamepad to be modified in the workshop with low force joysticks and buttons for a gamer with weak hand muscles to use.',
  },
  {
    amount: '£75',
    img: '/assets/img/donation-items/3f2cd0bf-3b0e-402d-9c59-a8fdbd73ff47.png',
    alt: 'Xbox Adaptive Controller',
    descHtml:
      'Will buy an interface box like an <a class="text-danger" href="https://www.xbox.com/en-GB/accessories/controllers/xbox-adaptive-controller" target="_blank" rel="noreferrer">Xbox Adaptive Controller</a> for use as part of a gaming setup.',
  },
  {
    amount: '£100',
    img: '/assets/img/donation-items/monstertech_table_mount_warthog_joystick_hero_1_-removebg-preview.png',
    alt: 'Mounting System',
    desc: 'Can enable us to buy a mounting system which will hold a joystick and position it for optimum use by a gamer to control it.',
  },
  {
    amount: '£200',
    img: '/assets/img/donation-items/img_01-removebg-preview.png',
    alt: 'Single Handed Controller',
    desc: 'Could buy a single handed controller to enable a disabled gamer to play with just one hand.',
  },
];

export function Donations() {
  return (
    <div className="d-flex flex-row min-vh-100">
      <div className="container donation-list-container p-3">
        <div className="h-100">
          <h3 className="text-bloodmoon mb-3">Thank you to all our donors!</h3>
          <p className="text-light">
            On behalf of everyone in the ZeldathonUK team we would like to thank all of
            the donors below for their generous donations:
          </p>

          {trackedDonations.length === 0 && (
            <div className="d-flex justify-content-center h-75">
              <div className="d-flex align-self-center">
                <div className="my-5">
                  <div className="d-flex justify-content-start">
                    <h6 className="text-bloodmoon">Make a donation</h6>
                  </div>
                  <DonationCards />
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="p-3 d-none d-xl-block">
        <div className="card bg-bloodmoon" style={{ width: '28rem' }}>
          <div className="text-center card card-header text-light">
            <h5 className="card-title text-bloodmoon mb-0" style={{ fontSize: '1.5em' }}>
              What could your donation do?
            </h5>
          </div>
          <div className="text-center card card-body small">
            <div className="text-light mb-3">
              <Link className="link-warning" to="/charity">
                SpecialEffect
              </Link>{' '}
              don't charge anything at all for their help. That's why your donations,
              large or small, really do count. Without your support they wouldn't be
              able to help people with physical disabilities to enjoy a better quality
              of life through their assessments, online resources and collaboration
              with key developers.
            </div>
            <table className="table text-white small mb-0">
              <tbody>
                {benefitRows.map((row) => (
                  <tr key={row.amount}>
                    <td style={{ verticalAlign: 'middle' }}>
                      <div className="donation-benefit-amount">{row.amount}</div>
                    </td>
                    <td style={{ verticalAlign: 'middle' }}>
                      <img className="donation-benefit-img" src={row.img} alt={row.alt} />
                    </td>
                    <td style={{ verticalAlign: 'middle' }}>
                      {row.descHtml ? (
                        <span
                          className="donation-benefit-desc"
                          dangerouslySetInnerHTML={{ __html: row.descHtml }}
                        />
                      ) : (
                        <span className="donation-benefit-desc">{row.desc}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
