// legacy/src/app/components/donations/donations.component.ts
import {Component, OnInit} from '@angular/core';
import TimeAgo from 'javascript-time-ago';
import en from 'javascript-time-ago/locale/en';
import {Observable} from 'rxjs';
import {map, pluck} from 'rxjs/operators';
import {DonationTrackingService} from '../../services/firebase/donation-tracking/donation-tracking.service';
import {TrackedDonation, TrackedDonationId} from '../../services/firebase/donation-tracking/tracked-donation';
import {ConfirmationService} from 'primeng/api';
import { faFacebook } from '@fortawesome/free-brands-svg-icons';


/**
 * COMPONENT IS DISPLAYED WITHIN THE DONATIONS PAGE
 */
@Component({
  selector: 'app-donations',
  templateUrl: './donations.component.html',
  styleUrls: ['./donations.component.css']
})
export class DonationsComponent implements OnInit {
  public timeAgo: TimeAgo;
  public trackedDonationIds$: Observable<TrackedDonation[]>;
  faFacebook = faFacebook;

  constructor( private donationTrackingService: DonationTrackingService,
               private confirmationService: ConfirmationService ) {
  }

  ngOnInit() {
    TimeAgo.addLocale(en);
    this.timeAgo = new TimeAgo('en-GB');
    this.trackedDonationIds$ = this.donationTrackingService.getTrackedDonationArray().pipe(
      map((trackedDonationId: TrackedDonationId[]) => trackedDonationId.find(x => x.id === 'DONATIONS')),
      pluck('donations'),
      map((trackedDonations: TrackedDonation[]) => {
        // console.log('trackedDonations:', trackedDonations);
        if (trackedDonations) {
          trackedDonations.sort((a: TrackedDonation, b: TrackedDonation) => b.donationAmount - a.donationAmount);
          for (const donation of trackedDonations) {
            donation.imgUrl = (donation.imgUrl === 'undefined' || donation.imgUrl === 'unknown' || donation.imgUrl === '')
              ? this.getRandomThumbnailImageUrl() : donation.imgUrl;
          }
          return trackedDonations;
        }
      })
    );
  }



  getRandomThumbnailImageUrl(): string {
    const imageUrls: string[] = [];
    imageUrls.push('../../../assets/img/thumbnails/ww-link-tingle.jpg');
    imageUrls.push('../../../assets/img/thumbnails/ss-fi-floating.jpg');
    imageUrls.push('../../../assets/img/thumbnails/oot-saria-avatar.jpg');
    imageUrls.push('../../../assets/img/thumbnails/botw-archer-link.jpg');
    imageUrls.push('../../../assets/img/thumbnails/botw-zelda-flower.jpg');
    imageUrls.push('../../../assets/img/thumbnails/z2-return-of-ganon.png');
    imageUrls.push('../../../assets/img/thumbnails/alttp-gannon-fight.jpg');
    imageUrls.push('../../../assets/img/thumbnails/tp-ganondorf-avatar.jpg');
    imageUrls.push('../../../assets/img/thumbnails/tp-goron-shop-owner.jpg');
    imageUrls.push('../../../assets/img/thumbnails/hylian-shield-avatar.jpg');
    imageUrls.push('../../../assets/img/thumbnails/mm-kid-link-keaton-mask.jpg');
    return imageUrls[Math.floor((Math.random() * imageUrls.length))];
  }

  getDateFromJustGivingString(dateStr: string): Date {
    const date1 = parseInt(dateStr.substring(6, dateStr.length - 7), 0);
    return new Date(date1);
  }

  confirm(event: Event) {
    this.confirmationService.confirm({
      target: event.target,
      icon: 'pi pi-exclamation-triangle',
      message: 'Don\'t be fooled by JustGivings "0% Platform Fee"! JustGiving charges non-profits a £39 (+VAT) monthly charge ' +
        'in addition to deducting a "Platform Processing Fee" of 1.9% + £0.20p fee from every donation. ' +
        'Finally JustGiving will further deduct 5% from any GiftAdd added by eligible UK tax payers.',
      accept: () => {
        this.donateJustGiving();
      },
      acceptLabel: 'Donate Anyway',
      acceptButtonStyleClass: 'p-button-warning',
      rejectLabel: 'Cancel',
      rejectButtonStyleClass: 'p-button-outlined p-button-secondary'
    });
  }

  donateFacebook() {
    window.open('https://www.facebook.com/donate/5194665980557244/?fundraiser_source=https://www.zeldathon.co.uk/', '_blank');
  }

  donateTiltify() {
    window.open('https://donate.tiltify.com/@msec/zeldathonuk-gameblast22', '_blank');
  }

  donateJustGiving() {
    window.open('https://www.justgiving.com/fundraising/zeldathonuk-gameblast2022', '_blank');
  }

  learnAboutSpecialEffect() {
    window.open('https://www.specialeffect.org.uk/what-we-do', '_blank');
  }

  learnAboutGameBlast() {
    window.open('https://www.gameblast.org.uk/about/', '_blank');
  }

}

<div class="d-flex flex-row min-vh-100">

  <div class="container donation-list-container p-3">

    <div class="h-100">
      <h3 class="text-bloodmoon mb-3">Thank you to all our donors!</h3>
      <p class="text-light">
        On behalf of everyone in the ZeldathonUK team we would like to thank all of the donors below for their generous donations:
      </p>

      <!--
      <pre>
        {{ (fundraisingPageDonations | async) | json }}
      </pre>
      -->

      <ng-container *ngIf="(trackedDonationIds$ | async) as tds">

        <ng-template [ngIf]="tds.length >= 1">
          <div class="min-vh-100">
            <ngx-masonry [options]="{ gutter: 10, percentPosition: true }" [ordered]="true">
              <div ngxMasonryItem style="width: 32.65%;" *ngFor="let donation of tds">
                <div class="card donor-list mb-2">

                  <div class="d-flex flex-column donation"
                       [ngClass]="donation.donationSource === 'Facebook' ? 'facebook-donation' :
                                  donation.donationSource === 'Tiltify' ? 'tiltify-donation' :
                                  donation.donationSource === 'JustGiving' ? 'justgiving-donation' : ''">

                    <div class="d-flex justify-content-between">
                      <div class="d-flex justify-content-start">
                        <div class="d-flex align-self-center">
                          <img class="donation-img"
                               [src]="donation.imgUrl"
                               [alt]="donation.name"
                               [title]="donation.name">
                        </div>
                        <div class="d-flex align-self-start ms-2">
                          <h5 class="mb-0" style="word-break: break-word;">{{ donation.name }}</h5>
                        </div>
                      </div>
                    </div>

                    <div class="my-2 small text-light" *ngIf="donation.message !== null && donation.message.length >= 1">
                      <span class="position-relative" style="font-size: 2em; font-family: 'Poppins', sans-serif; top: 0.2em;">&ldquo;</span>
                      <i class="px-1" style="font-size: 1.2em; font-family: 'Poppins', sans-serif;">{{ donation.message.length >= 1 ? donation.message : '-' }}</i>
                      <span class="position-relative" style="font-size: 2em; font-family: 'Poppins', sans-serif; top: 0.7em;">&rdquo;</span>
                    </div>

                    <div class="d-flex justify-content-between">
                      <div class="d-flex align-self-end">
                        <div class="badge rounded-pill bg-success" *ngIf="donation.giftAidAmount">
                          <a href="https://www.gov.uk/donating-to-charity/gift-aid" target="_blank" class="text-white"
                             title="Gift Aid declaration made for the charity to claim additional 25% of donation">GiftAid</a>: {{ donation.giftAidAmount | currency:donation.currency }}
                        </div>
                      </div>
                      <div class="">
                        <h1 class="mb-0" style="font-family: 'Bungee', cursive;">{{ donation.donationAmount | currency:donation.currency }}</h1>
                      </div>
                    </div>

                    <div class="d-flex justify-content-end">
                      <span class="text-white-50" style="font-size: 0.8em;">{{ timeAgo.format(donation.donationDate.toDate()) }}</span>
                    </div>

                  </div>

                </div>
              </div>
            </ngx-masonry>
          </div>
        </ng-template>

        <ng-template [ngIf]="tds.length === 0">
          <div class="d-flex justify-content-center h-75">
            <div class="d-flex align-self-center">

              <div class="my-5">

                <div class="d-flex justify-content-start">
                  <h6 class="text-bloodmoon">Make a donation</h6>
                </div>

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">

                  <div class="col">
                    <div class="d-flex btn btn-bloodmoon" (click)="donateFacebook();" title="Donate via Facebook">
                      <div class="d-flex flex-column flex-md-row flex-fill">
                        <div class="flex-grow-1 justify-content-center align-self-center">
                          <h4 class="text-nowrap mb-0" style="font-family: 'Bungee', cursive;">
                            <fa-icon [icon]="faFacebook"></fa-icon>&nbsp;Donate
                          </h4>
                          <div class="text-center small">
                            <span class="d-block font-italic small">using Facebook</span>
                          </div>
                        </div>
                        <div class="">
                          <div class="d-flex flex-row flex-md-column justify-content-evenly">
                            <div class="mb-md-1">
                              <a class="btn btn-outline-light btn-sm" href="https://www.facebook.com/help/901370616673951" target="_blank"
                                 title="More info on JustGiving Fundraising Fees" style="font-size: 0.65em;">Fees</a>
                            </div>
                            <div class="">
                              <a class="btn btn-outline-light btn-sm" href="https://www.facebook.com/help/728799837303698" target="_blank"
                                 title="More info on GiftAid" style="font-size: 0.65em;">GiftAid</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col">
                    <div class="d-flex btn btn-bloodmoon" (click)="donateTiltify();" title="Donate via Tiltify">
                      <div class="d-flex flex-column flex-md-row flex-fill">
                        <div class="flex-grow-1 justify-content-center align-self-center">
                          <h4 class="text-nowrap mb-0" style="font-family: 'Bungee', cursive;">
                            <div class="d-inline-block" style="position: relative; width: .9em;">
                              <img style="max-width: .9em; padding-bottom: .25em; filter: brightness(10);"
                                   src="../../../assets/img/Tiltify_Logo.png" alt="Tiltify logo">
                            </div> Donate
                          </h4>
                          <div class="text-center small">
                            <span class="d-block font-italic small">using Tiltify</span>
                          </div>
                        </div>
                        <div class="">
                          <div class="d-flex flex-row flex-md-column justify-content-evenly">
                            <div class="mb-md-1">
                              <a class="btn btn-outline-light btn-sm" href="https://info.tiltify.com/support/solutions/articles/43000045885-what-are-the-fees-" target="_blank"
                                 title="More info on Tiltify Fees" style="font-size: 0.65em;">Fees</a>
                            </div>
                            <div class="">
                              <a class="btn btn-outline-light btn-sm" href="https://www.gov.uk/claim-gift-aid/gift-aid-declarations" target="_blank"
                                 title="More info on GiftAid" style="font-size: 0.65em;">GiftAid</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col">
                    <div class="">
                      <p-confirmPopup [styleClass]="'w-50'"></p-confirmPopup>
                    </div>
                    <div class="d-flex btn btn-bloodmoon" (click)="confirm($event);" title="Donate via JustGiving">
                      <div class="d-flex flex-column flex-md-row flex-fill">
                        <div class="flex-grow-1 justify-content-center align-self-center">
                          <h4 class="text-nowrap mb-0" style="font-family: 'Bungee', cursive;">
                            <div class="d-inline-block" style="position: relative; width: .9em;">
                              <img style="max-width: .9em; padding-bottom: .25em; filter: brightness(10);"
                                   src="../../../assets/img/justgiving-g.svg" alt="JustGiving logo">
                            </div> Donate
                          </h4>
                          <div class="text-center small">
                            <span class="d-block font-italic small">using JustGiving</span>
                          </div>
                        </div>
                        <div class="">
                          <div class="d-flex flex-row flex-md-column justify-content-evenly">
                            <div class="mb-md-1">
                              <a class="btn btn-outline-light btn-sm" href="https://www.justgiving.com/info/fees" target="_blank"
                                 title="More info on JustGiving Fundraising Fees" style="font-size: 0.65em;">Fees</a>
                            </div>
                            <div class="">
                              <a class="btn btn-outline-light btn-sm" href="https://help.justgiving.com/hc/en-us/articles/200670391-A-guide-to-Gift-Aid-UK-only-" target="_blank"
                                 title="More info on GiftAid" style="font-size: 0.65em;">GiftAid</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col">

                    <div class="d-flex btn btn-bloodmoon h-100" (click)="learnAboutGameBlast();"
                         title="Find out more about the GameBlast event">
                      <div class="d-flex flex-column flex-md-row flex-fill">
                        <div class="flex-grow-1 align-self-center">
                          <h4 class=" text-center">
                            <img src="../../../assets/img/GB22_Logo_Linear_DarkBGs_Small.png"
                                 alt="gameblast22 logo" style="max-height: 2rem;">
                          </h4>
                        </div>
                        <div class="align-self-center">
                          <div class="small text-white">
                            <span class="d-block small fw-bolder">25-27<sup>th</sup> Feb 2022</span>
                            <span class="d-block small">The UK's Biggest Charity Gaming Weekend</span>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>

                </div>
              </div>

            </div>
          </div>
        </ng-template>

      </ng-container>
    </div>

  </div>

  <div class="p-3 d-none d-xl-block">
    <div class="card bg-bloodmoon" style="width: 28rem;">
      <div class="text-center card card-header text-light">
        <h5 class="card-title text-bloodmoon mb-0" style="font-size: 1.5em;">What could your donation do?</h5>
      </div>
      <div class="text-center card card-body small">
        <div class="text-light mb-3">
          <a class="link-warning" [routerLink]="'/charity'">SpecialEffect</a> don’t charge anything at all for their help. That’s why your donations, large or small, really do count. Without your support they wouldn’t be able to help people with physical disabilities to enjoy a better quality of life through their assessments, online resources and collaboration with key developers. Whether your involvement is through a donation of time, skills, or funds, your support is absolutely crucial to the charity’s future impact and success.
        </div>
        <table class="table text-white small mb-0">
          <tbody>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;5
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/xbox-controller-technology-games-design_dezeen_2364_col_23_1_-removebg-preview.png"
                   alt="Flexible Fixings">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Can buy flexible fixings to enable a correct and firm hold of controller, joystick or button for safe and comfortable use.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;10
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/infinity4ps-thumbstick-heights-removebg-preview.png"
                   alt="Joystick Extensions">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Could purchase joystick extensions, to potentially enable greater control of a thumbstick, with its increased leverage.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;25
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/sasha_setup-e1628153142123-removebg-preview.png"
                   alt="Deliver Adaptive Gaming Setup">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Will enable us to deliver an adapted gaming setup quickly and directly to someone who needs it.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;50
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/2_ALT_MiniJoystick-min-removebg-preview.png"
                   alt="Low Force Joysticks">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Will buy a gamepad to be modified in the workshop with low force joysticks and buttons for a gamer with weak hand muscles to use.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;75
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/3f2cd0bf-3b0e-402d-9c59-a8fdbd73ff47.png"
                   alt="Xbox Adaptive Controller">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Will buy an interface box like an
                <a class="text-danger" href="https://www.xbox.com/en-GB/accessories/controllers/xbox-adaptive-controller" target="_blank">Xbox Adaptive Controller</a>
                for use as part of a gaming setup.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;100
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/monstertech_table_mount_warthog_joystick_hero_1_-removebg-preview.png"
                   alt="Mounting System">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Can enable us to buy a mounting system which will hold a joystick and position it for optimum use by a gamer to control it.</span>
            </td>
          </tr>
          <tr>
            <td style="vertical-align: middle;">
              <div class="donation-benefit-amount">
                &pound;200
              </div>
            </td>
            <td style="vertical-align: middle;">
              <img class="donation-benefit-img"
                   src="../../../assets/img/donation-items/img_01-removebg-preview.png"
                   alt="Single Handed Controller">
            </td>
            <td style="vertical-align: middle;">
              <span class="donation-benefit-desc">Could buy a single handed controller to enable a disabled gamer to play with just one hand.</span>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>

// frontend/src/routes/Donations.tsx
import { Link } from 'react-router';
import { DonationCards } from '@/components/DonationCards';
import './donations.css';

/**
 * Real donor data was sourced from Firebase. Until the Django backend is
 * wired up the donor list is empty and the page renders the legacy
 * "empty state" view (donate-cards + SpecialEffect benefits sidebar).
 */
const trackedDonations: unknown[] = [];

const benefitRows = [
  {
    amount: '£5',
    img: '/assets/img/donation-items/xbox-controller-technology-games-design_dezeen_2364_col_23_1_-removebg-preview.png',
    alt: 'Flexible Fixings',
    desc: 'Can buy flexible fixings to enable a correct and firm hold of controller, joystick or button for safe and comfortable use.',
  },
  {
    amount: '£10',
    img: '/assets/img/donation-items/infinity4ps-thumbstick-heights-removebg-preview.png',
    alt: 'Joystick Extensions',
    desc: 'Could purchase joystick extensions, to potentially enable greater control of a thumbstick, with its increased leverage.',
  },
  {
    amount: '£25',
    img: '/assets/img/donation-items/sasha_setup-e1628153142123-removebg-preview.png',
    alt: 'Deliver Adaptive Gaming Setup',
    desc: 'Will enable us to deliver an adapted gaming setup quickly and directly to someone who needs it.',
  },
  {
    amount: '£50',
    img: '/assets/img/donation-items/2_ALT_MiniJoystick-min-removebg-preview.png',
    alt: 'Low Force Joysticks',
    desc: 'Will buy a gamepad to be modified in the workshop with low force joysticks and buttons for a gamer with weak hand muscles to use.',
  },
  {
    amount: '£75',
    img: '/assets/img/donation-items/3f2cd0bf-3b0e-402d-9c59-a8fdbd73ff47.png',
    alt: 'Xbox Adaptive Controller',
    descHtml:
      'Will buy an interface box like an <a class="text-danger" href="https://www.xbox.com/en-GB/accessories/controllers/xbox-adaptive-controller" target="_blank" rel="noreferrer">Xbox Adaptive Controller</a> for use as part of a gaming setup.',
  },
  {
    amount: '£100',
    img: '/assets/img/donation-items/monstertech_table_mount_warthog_joystick_hero_1_-removebg-preview.png',
    alt: 'Mounting System',
    desc: 'Can enable us to buy a mounting system which will hold a joystick and position it for optimum use by a gamer to control it.',
  },
  {
    amount: '£200',
    img: '/assets/img/donation-items/img_01-removebg-preview.png',
    alt: 'Single Handed Controller',
    desc: 'Could buy a single handed controller to enable a disabled gamer to play with just one hand.',
  },
];

export function Donations() {
  return (
    <div className="d-flex flex-row min-vh-100">
      <div className="container donation-list-container p-3">
        <div className="h-100">
          <h3 className="text-bloodmoon mb-3">Thank you to all our donors!</h3>
          <p className="text-light">
            On behalf of everyone in the ZeldathonUK team we would like to thank all of
            the donors below for their generous donations:
          </p>

          {trackedDonations.length === 0 && (
            <div className="d-flex justify-content-center h-75">
              <div className="d-flex align-self-center">
                <div className="my-5">
                  <div className="d-flex justify-content-start">
                    <h6 className="text-bloodmoon">Make a donation</h6>
                  </div>
                  <DonationCards />
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="p-3 d-none d-xl-block">
        <div className="card bg-bloodmoon" style={{ width: '28rem' }}>
          <div className="text-center card card-header text-light">
            <h5 className="card-title text-bloodmoon mb-0" style={{ fontSize: '1.5em' }}>
              What could your donation do?
            </h5>
          </div>
          <div className="text-center card card-body small">
            <div className="text-light mb-3">
              <Link className="link-warning" to="/charity">
                SpecialEffect
              </Link>{' '}
              don't charge anything at all for their help. That's why your donations,
              large or small, really do count. Without your support they wouldn't be
              able to help people with physical disabilities to enjoy a better quality
              of life through their assessments, online resources and collaboration
              with key developers.
            </div>
            <table className="table text-white small mb-0">
              <tbody>
                {benefitRows.map((row) => (
                  <tr key={row.amount}>
                    <td style={{ verticalAlign: 'middle' }}>
                      <div className="donation-benefit-amount">{row.amount}</div>
                    </td>
                    <td style={{ verticalAlign: 'middle' }}>
                      <img className="donation-benefit-img" src={row.img} alt={row.alt} />
                    </td>
                    <td style={{ verticalAlign: 'middle' }}>
                      {row.descHtml ? (
                        <span
                          className="donation-benefit-desc"
                          dangerouslySetInnerHTML={{ __html: row.descHtml }}
                        />
                      ) : (
                        <span className="donation-benefit-desc">{row.desc}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
