// src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/firebase/auth/auth.service';
import { Router } from '@angular/router';
import { User } from 'firebase';
import { faGoogle } from "@fortawesome/free-brands-svg-icons";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  private currentUser: User;
  public faGoogle = faGoogle;

  constructor(private authService: AuthService,
              private router: Router) {
    this.authService.user$.subscribe(user => {
      console.log('Logged in: ', user);
      this.currentUser = user;
      this.router.navigateByUrl('');
    });
  }

  ngOnInit() {
    if (this.currentUser !== undefined && this.currentUser !== null) {
      console.log('logged in');
    } else if (this.currentUser === undefined || this.currentUser === null) {
      console.log('not logged in');
    }
  }

  login() {
    this.authService.login('google');
  }

  showPrivacyPolicyModal() {
    //
  }

  showTermsOfServiceModal() {
    //
  }

}

<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="card border-primary w-50">
      <div class="card-header d-flex pb-1">
        <img class="align-self-center" src="https://www.gstatic.com/images/branding/googlelogo/svg/googlelogo_clr_74x24px.svg">
        <span class="align-self-center ml-1 mb-1" style="font-size: large;">Account</span>
      </div>
      <div class="card-body bg-light">
        <!--
        <div class="form-group">
          <label class="col-form-label col-form-label-lg" for="inputEmail">Email:</label>
          <input class="form-control form-control-lg" type="text" placeholder="email.address@gmail.com" id="inputEmail">
        </div>
        <div class="form-group">
          <label class="col-form-label col-form-label-lg" for="inputPassword">Password:</label>
          <input class="form-control form-control-lg" type="password" placeholder="Password" id="inputPassword">
        </div>
        -->
        <div class="form-group text-center">
          <button class="btn btn-lg btn-primary my-2 w-50" type="submit" (click)="login()" title="Login with your Google Account">Login with <fa-icon [icon]="faGoogle"></fa-icon></button>
        </div>
      </div>
      <div class="card-footer">
        <span class="small">By logging in using your Google account you agree to our <span class="text-info" (click)="showPrivacyPolicyModal()">privacy policy</span> and <span class="text-info" (click)="showTermsOfServiceModal()">terms of service</span>.
          Google provide us with your name, email address and profile picture.
          You can revoke our access to your account data any time from your <a class="text-muted" href="https://myaccount.google.com/permissions" target="_blank">
            <span class="text-primary">G</span>
            <span class="text-danger">o</span>
            <span class="text-warning">o</span>
            <span class="text-primary">g</span>
            <span class="text-success">l</span>
            <span class="text-danger">e</span>
            Account
          </a>.</span>
      </div>
    </div>
  </div>
</div>

// frontend/src/routes/Login.tsx
import { useState } from 'react';

export function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const submit = () => {
    // Auth backend not wired yet — placeholder for Clerk integration.
    console.warn('Login submitted but auth is disabled.', { email });
  };

  return (
    <div className="container mt-3">
      <div className="row d-flex justify-content-center">
        <div className="card border-primary w-50">
          <div className="card-header d-flex pb-1">
            <img
              className="align-self-center"
              src="https://www.gstatic.com/images/branding/googlelogo/svg/googlelogo_clr_74x24px.svg"
              alt="Google"
            />
            <span className="align-self-center ms-1 mb-1" style={{ fontSize: 'large' }}>
              Account
            </span>
          </div>
          <div className="card-body bg-light">
            <div className="form-group">
              <label className="col-form-label col-form-label-lg" htmlFor="inputEmail">
                Email:
              </label>
              <input
                className="form-control form-control-lg"
                type="text"
                placeholder="email.address@gmail.com"
                id="inputEmail"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className="form-group">
              <label
                className="col-form-label col-form-label-lg"
                htmlFor="inputPassword"
              >
                Password:
              </label>
              <input
                className="form-control form-control-lg"
                type="password"
                placeholder="Password"
                id="inputPassword"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
            <div className="form-group text-center">
              <button
                className="btn btn-lg btn-primary my-2 w-50"
                type="submit"
                onClick={submit}
                title="Login with your Google Account"
              >
                Login with Google
              </button>
            </div>
          </div>
          <div className="card-footer">
            <span className="small">
              By logging in using your Google account you agree to our{' '}
              <span className="text-info" role="button" tabIndex={0}>
                privacy policy
              </span>{' '}
              and{' '}
              <span className="text-info" role="button" tabIndex={0}>
                terms of service
              </span>
              . Google provide us with your name, email address and profile picture. You
              can revoke our access to your account data any time from your{' '}
              <a
                className="text-muted"
                href="https://myaccount.google.com/permissions"
                target="_blank"
                rel="noreferrer"
              >
                <span className="text-primary">G</span>
                <span className="text-danger">o</span>
                <span className="text-warning">o</span>
                <span className="text-primary">g</span>
                <span className="text-success">l</span>
                <span className="text-danger">e</span> Account
              </a>
              .
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
