// src/app/components/schedule/schedule.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { TwitchService } from '../../services/twitch-service/twitch-service.service';

import { faFacebook } from '@fortawesome/free-brands-svg-icons';


@Component({
  selector: 'app-schedule',
  templateUrl: './schedule.component.html',
  styleUrls: ['./schedule.component.css']
})
export class ScheduleComponent implements OnInit {

  public gameList: Game[];

  faFacebook = faFacebook;

  public now: Date;
  public isLive = false;

  constructor(private router: Router,
              private twitchService: TwitchService) {
  }

  ngOnInit() {
    this.now = new Date();
    this.gameList = this.getGames();

    this.twitchService.getSearchChannels('zeldathonuk', 1, false).subscribe(data => {
      this.isLive = data.is_live;
    });

  }

  routeToLiveView() {
    this.router.navigate(['']).then();
  }

  isCurrentlyPlaying(index: number): boolean {
    return (this.gameList[index].startDate.getTime() <= this.now.getTime() &&
      this.gameList[index + 1]?.startDate.getTime() > this.now.getTime());
  }

  hasBeenPlayed(index: number): boolean {
    return (this.gameList[index]?.startDate.getTime() <= this.now.getTime());
  }

  donateFacebook() {
    window.open('https://www.facebook.com/donate/5194665980557244/?fundraiser_source=https://www.zeldathon.co.uk/', '_blank');
  }

  donateJustGiving() {
    window.open('https://www.justgiving.com/fundraising/zeldathonuk-gameblast2022', '_blank');
  }

  getGames(): Game[] {
    const games: Game[] = [];
    const skywardSword = {
      startDate: new Date('2021-02-20 09:00:00'),
      console: 'Wii',
      timeline: 'Original',
      name: 'The Legend of Zelda: Skyward Sword',
      releaseDate: 2011,
      boxArt: '../../../assets/img/cover-art/ss_cover.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '24 Hours',
          url: 'https://howlongtobeat.com/game?id=10042'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(skywardSword);

    const minishCap = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'GBA',
      name: 'The Legend of Zelda: The Minish Cap',
      timeline: 'Original',
      releaseDate: 2004,
      boxArt: '../../../assets/img/cover-art/Minish_Cap_cover.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '15 Hours',
          url: 'https://howlongtobeat.com/game.php?id=10044'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(minishCap);

    const fourSwordsAnniversaryEdition = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: '3DS',
      timeline: 'Original',
      name: 'The Legend of Zelda: Four Swords',
      releaseDate: 2004,
      boxArt: '../../../assets/img/cover-art/250px-Zelda_fsae.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-secondary',
          text: '4P Co-op'
        },
        {
          type: 'bg-info',
          text: '4 Hours',
          url: 'https://howlongtobeat.com/game?id=10031'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(fourSwordsAnniversaryEdition);

    const ocarinaOfTime = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'N64',
      timeline: 'Original',
      name: 'The Legend of Zelda: Ocarina of Time',
      releaseDate: 1998,
      boxArt: '../../../assets/img/cover-art/250px-ZeldaOoTbox.jpg',
      extraBadges: [{
        type: 'bg-primary',
        text: 'Multiplayer Any%'
        },
        {
          type: 'bg-success',
          text: 'OoT Online',
          url: 'https://github.com/hylian-modding/OcarinaOfTimeOnline'
        },
        {
          type: 'bg-info',
          text: '10 Hours',
          url: 'https://howlongtobeat.com/game?id=10035'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(ocarinaOfTime);

    const majorasMask = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'N64',
      timeline: 'Child',
      name: 'The Legend of Zelda: Majora\'s Mask',
      releaseDate: 2000,
      boxArt: '../../../assets/img/cover-art/Majoras_Mask_3D_cover.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Multiplayer Any%'
        },
        {
          type: 'bg-success',
          text: 'MM Online',
          url: 'https://github.com/hylian-modding/MajorasMaskOnline'
        },
        {
          type: 'bg-info',
          text: '10 Hours',
          url: 'https://howlongtobeat.com/game?id=10034'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(majorasMask);

    const twilightPrincessHd = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'WiiU',
      timeline: 'Child',
      name: 'The Legend of Zelda: Twilight Princess HD',
      releaseDate: 2016,
      boxArt: '../../../assets/img/cover-art/Twilight_Princess_HD_cover.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '20 Hours',
          url: 'https://howlongtobeat.com/game?id=33835'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(twilightPrincessHd);

    const fourSwordsAdventure = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'GC',
      timeline: 'Child',
      name: 'The Legend of Zelda: Four Swords Adventures',
      releaseDate: 2004,
      boxArt: '../../../assets/img/cover-art/250px-Zeldafourswordsbox.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-secondary',
          text: '4P Co-op'
        },
        {
          type: 'bg-info',
          text: '15 Hours',
          url: 'https://howlongtobeat.com/game?id=10030'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(fourSwordsAdventure);

    const windWakerHd = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'WiiU',
      timeline: 'Adult',
      name: 'The Legend of Zelda: The Wind Waker HD',
      releaseDate: 2013,
      boxArt: '../../../assets/img/cover-art/Zelda_TheWindWakerHD.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '25 Hours',
          url: 'https://howlongtobeat.com/game?id=13142'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(windWakerHd);

    const phantomHourglass = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'DS',
      timeline: 'Adult',
      name: 'The Legend of Zelda: Phantom Hourglass',
      releaseDate: 2007,
      boxArt: '../../../assets/img/cover-art/phantom-hourglass-cover-256.png',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '16 Hours',
          url: 'https://howlongtobeat.com/game?id=10041'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(phantomHourglass);

    const spiritTracks = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'DS',
      timeline: 'Adult',
      name: 'The Legend of Zelda: Spirit Tracks',
      releaseDate: 2009,
      boxArt: '../../../assets/img/cover-art/Spirit_Tracks_cover.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '19 Hours',
          url: 'https://howlongtobeat.com/game?id=10043'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(spiritTracks);

    const linkToThePast = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'SNES',
      timeline: 'Downfall',
      name: 'The Legend of Zelda: A Link to the Past',
      releaseDate: 1992,
      boxArt: '../../../assets/img/cover-art/250px-Zelda_SNES.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Multiplayer Any%'
        },
        {
          type: 'bg-success',
          text: 'ALttP Online',
          url: 'https://github.com/alttpo/alttpo'
        },
        {
          type: 'bg-info',
          text: '15 Hours',
          url: 'https://howlongtobeat.com/game?id=10028'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(linkToThePast);

    const linksAwakeningSwitch = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'Switch',
      timeline: 'Downfall',
      name: 'The Legend of Zelda: Link\'s Awakening',
      releaseDate: 2019,
      boxArt: '../../../assets/img/cover-art/66255_The_Legend_of_Zelda_Links_Awakening_(2019).jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '14 Hours',
          url: 'https://howlongtobeat.com/game?id=66255'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(linksAwakeningSwitch);

    const linkBetweenWorlds = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: '3DS',
      timeline: 'Downfall',
      name: 'The Legend of Zelda: A Link Between Worlds',
      releaseDate: 2013,
      boxArt: '../../../assets/img/cover-art/d6qewmw-4f881e91-6d83-46bb-9deb-2140a7266d69.png',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '16 Hours',
          url: 'https://howlongtobeat.com/game.php?id=12965'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(linkBetweenWorlds);

    const triforceHeroes = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: '3DS',
      timeline: 'Downfall',
      name: 'The Legend of Zelda: Tri Force Heroes',
      releaseDate: 2015,
      boxArt: '../../../assets/img/cover-art/250px-Zelda_triforce-heroes.jpg',
      extraBadges: [{
        type: 'bg-primary',
        text: 'Any%'
      },
        {
          type: 'bg-info',
          text: '14 Hours',
          url: 'https://howlongtobeat.com/game?id=30592'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(triforceHeroes);

    const theLegendOfZelda = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'NES',
      timeline: 'Downfall',
      name: 'The Legend of Zelda',
      releaseDate: 1986,
      boxArt: '../../../assets/img/cover-art/Legend_of_zelda_cover_(with_cartridge)_gold.png',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '8 Hours',
          url: 'https://howlongtobeat.com/game?id=10025'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(theLegendOfZelda);

    const zeldaIITheAdventureOfLink = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'NES',
      timeline: 'Downfall',
      name: 'Zelda II: The Adventure of Link',
      releaseDate: 1987,
      boxArt: '../../../assets/img/cover-art/Adventure_of_Link_cover.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-info',
          text: '11 Hours',
          url: 'https://howlongtobeat.com/game.php?id=11533'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(zeldaIITheAdventureOfLink);

    const hyruleWarriorsAgeOfCalamity = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'Switch',
      timeline: '???',
      name: 'Hyrule Warriors: Age of Calamity',
      releaseDate: 2020,
      boxArt: '../../../assets/img/cover-art/hyrule-warriors-age-of-calamity-cover.cover_small.jpg',
      extraBadges: [{
          type: 'bg-primary',
          text: 'Any%'
        },
        {
          type: 'bg-danger',
          text: 'New Title',
          url: 'https://www.nintendo.co.uk/Games/Nintendo-Switch/Hyrule-Warriors-Age-of-Calamity-1838129.html'
        },
        {
          type: 'bg-info',
          text: '20 Hours',
          url: 'https://howlongtobeat.com/game?id=82895'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(hyruleWarriorsAgeOfCalamity);

    const breathOfTheWild = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'Switch',
      timeline: '???',
      name: 'The Legend of Zelda: Breath of the Wild',
      releaseDate: 2017,
      boxArt: '../../../assets/img/cover-art/38019_The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
      extraBadges: [{
        type: 'bg-primary',
        text: 'Any%'
      },
        {
          type: 'bg-info',
          text: '18 Hours',
          url: 'https://howlongtobeat.com/game?id=38019'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(breathOfTheWild);

    const linkToThePastSuperMetroidRandomizer = {
      startDate: new Date((games[games.length - 1].startDate.getTime() +
        (parseInt(games[games.length - 1].extraBadges.find(x => x.text.endsWith('Hours')).text.split(' ')[0], 10) * 60 * 60 * 1000))),
      console: 'SNES',
      timeline: 'Crossover',
      name: 'Super Metroid & A Link to the Past Crossover Item Randomizer',
      releaseDate: 1992,
      boxArt: '../../../assets/img/cover-art/250px-Zelda_SNES_Metroid.jpg',
      extraBadges: [{
        type: 'bg-primary',
        text: 'Multiplayer Any%'
      },
        {
          type: 'bg-danger',
          text: 'Randomizer',
          url: 'https://github.com/tewtal/SMZ3Randomizer'
        },
        {
          type: 'bg-info',
          text: '14 Hours',
          url: 'https://howlongtobeat.com/game?id=10028'
        }],
      runners: [{
        name: 'MSec',
        channelUrl: 'https://www.twitch.tv/msec'
      }],
    };
    games.push(linkToThePastSuperMetroidRandomizer);

    return games;
  }

}


interface Game {
  startDate: Date;
  console: string;
  name: string;
  timeline: string;
  releaseDate: number;
  boxArt: string;
  extraBadges: Badge[];
  runners: Runner[];
}

interface Badge {
  type: string;
  text: string;
  url?: string;
}

interface Runner {
  name: string;
  channelUrl: string;
}

<div class="d-flex flex-row min-vh-100">

  <div class="container p-3 min-vh-100" >

    <div class="py-2">
      <h3 class="text-white">Stream Schedule</h3>

      <p class="text-light">
        This year our line up will be following the <a class="text-info" href="https://www.zelda.com/about/" target="_blank">Official Zelda Timeline</a> as closely as possible.
        Check the dates and times below to see when (roughly) we will be playing your favourite titles so that you won't miss out!
      </p>

      <div class="table-responsive">
        <table class="table table-hover table-striped table-dark" style="font-size: 12px;">
          <thead>
            <tr>
              <th scope="col">Day</th>
              <th scope="col">Time</th>
              <th scope="col">
                <div class="d-none d-md-block">
                  Console
                </div>
              </th>
              <th scope="col">
                <div class="d-none d-md-block">
                  Timeline
                </div>
              </th>
              <th scope="col">Game</th>
              <th scope="col">
                <div class="d-none d-md-block">
                  Runner(s)
                </div>
              </th>
            </tr>
          </thead>
          <tbody>

            <tr *ngFor="let game of gameList; let i = index" [ngClass]="isCurrentlyPlaying(i) ? 'table-gold' : hasBeenPlayed(i) ? 'table-played' : ''">

              <td class="align-middle">
                <div class="">
                  {{ game.startDate | date:'EEE dd' }}
                </div>
                <div class="text-white-50">
                  {{ game.startDate | date:'MMM yyyy' }}
                </div>
              </td>

              <td class="align-middle">
                <div class="">
                  {{ game.startDate | date:'hh:mm' }}
                </div>
                <div class="text-white-50">
                  {{ game.startDate | date:'aa' }}
                </div>
              </td>

              <td class="align-middle text-center">
                <div class="d-none d-md-block">
                  <div class="badge rounded-pill bg-secondary p-2">
                    {{ game.console }}
                  </div>
                </div>
              </td>

              <td class="align-middle text-center">
                <div class="d-none d-md-block">
                  <div class="badge rounded-pill bg-light text-black p-2">
                    {{ game.timeline }}
                  </div>
                </div>
              </td>

              <td class="align-middle">
                <div class="d-flex justify-content-between align-items-center">
                  <div class="d-flex flex-column me-2">
                    <img [src]="game.boxArt" [alt]="game.name + ' Cover Art'" style="max-width: 50px;"
                         [title]="game.name + ' Cover Art'">
                  </div>
                  <div class="text-center w-100">
                    <div class="mb-1">
                      {{ game.name }} ({{ game.releaseDate }})
                      <ng-container *ngIf="hasBeenPlayed(i) && !isCurrentlyPlaying(i)">
                          <span class="badge bg-warning m-2">
                            COMPLETED
                          </span>
                      </ng-container>
                      <ng-container *ngIf="isCurrentlyPlaying(i) && isLive">
                        <div class="d-inline-block m-2" (click)="routeToLiveView()">
                              <span class="badge bg-danger" style="cursor: pointer;" title="Watch Livestream">
                                LIVE <span style="color: red;">🔴</span>
                              </span>
                          <div class="d-inline-block live-circle ms-1"></div>
                        </div>
                      </ng-container>
                    </div>
                    <ng-container *ngFor="let badge of game.extraBadges">
                      <ng-container *ngIf="badge.url">
                          <span class="badge m-2" [ngClass]="badge.type">
                            <a class="text-white" [href]="badge.url" target="_blank">{{ badge.text }}</a>
                          </span>
                      </ng-container>
                      <ng-container *ngIf="!badge.url">
                          <span class="badge m-2" [ngClass]="badge.type">
                            {{ badge.text }}
                          </span>
                      </ng-container>
                    </ng-container>
                  </div>
                </div>
              </td>

              <td class="align-middle text-center">
                <div class="d-none d-md-block">
                  <ng-container *ngFor="let runner of game.runners">
                    <a [href]="runner.channelUrl" target="_blank"><span class="badge rounded-pill bg-secondary p-2">{{ runner.name }}</span></a>
                  </ng-container>
                </div>
              </td>

            </tr>

          </tbody>
        </table>
      </div>

    </div>

  </div>

</div>

// frontend/src/routes/Schedule.tsx
import moment from 'moment';
import { useMemo } from 'react';
import './schedule.css';

type Runner = { name: string; channelUrl: string };
type Badge = { name: string; type: string; tooltip: string; url?: string };
type ScheduledGame = {
  gameProgressKey: string;
  title: string;
  releaseYear: string;
  boxArt: string;
  platform: string;
  runners: Runner[];
  badges: Badge[];
  durationHours: number;
  durationMinutes: number;
  howLongToBeatId: string;
  isCompleted?: boolean;
};

/**
 * Placeholder GameBlast22 schedule. Mirrors the shape the legacy Firebase
 * `gameLineupService` returned. Will be replaced with a live read from the
 * Django backend once the schema is in place.
 */
const startDate = new Date('2022-02-25T17:00:00+00:00');
const currentGameKey = '';
const isLive = false;

const games: ScheduledGame[] = [
  {
    gameProgressKey: 'wind-waker',
    title: 'The Legend of Zelda: The Wind Waker HD',
    releaseYear: '2013',
    boxArt:
      'https://howlongtobeat.com/games/Wind_Waker_HD.jpg',
    platform: 'Wii U',
    runners: [{ name: 'msec', channelUrl: 'https://www.twitch.tv/msec' }],
    badges: [],
    durationHours: 12,
    durationMinutes: 0,
    howLongToBeatId: '4138',
  },
  {
    gameProgressKey: 'ocarina-of-time',
    title: 'The Legend of Zelda: Ocarina of Time',
    releaseYear: '1998',
    boxArt: 'https://howlongtobeat.com/games/Ocarina_of_Time.jpg',
    platform: 'N64',
    runners: [
      { name: 'msec', channelUrl: 'https://www.twitch.tv/msec' },
      { name: 'lottie', channelUrl: '' },
    ],
    badges: [
      { name: '100%', type: 'bg-warning text-dark', tooltip: 'Going for 100% completion' },
    ],
    durationHours: 14,
    durationMinutes: 30,
    howLongToBeatId: '4456',
  },
  {
    gameProgressKey: 'majoras-mask',
    title: "The Legend of Zelda: Majora's Mask",
    releaseYear: '2000',
    boxArt: 'https://howlongtobeat.com/games/Majoras_Mask.jpg',
    platform: 'N64',
    runners: [{ name: 'msec', channelUrl: 'https://www.twitch.tv/msec' }],
    badges: [],
    durationHours: 10,
    durationMinutes: 0,
    howLongToBeatId: '4459',
  },
  {
    gameProgressKey: 'breath-of-the-wild',
    title: 'The Legend of Zelda: Breath of the Wild',
    releaseYear: '2017',
    boxArt: 'https://howlongtobeat.com/games/Breath_of_the_Wild.jpg',
    platform: 'Switch',
    runners: [
      { name: 'msec', channelUrl: 'https://www.twitch.tv/msec' },
      { name: 'henry', channelUrl: '' },
    ],
    badges: [
      { name: 'Boss Rush', type: 'bg-danger', tooltip: 'All-bosses run' },
    ],
    durationHours: 8,
    durationMinutes: 0,
    howLongToBeatId: '38050',
  },
  {
    gameProgressKey: 'skyward-sword',
    title: 'The Legend of Zelda: Skyward Sword HD',
    releaseYear: '2021',
    boxArt: 'https://howlongtobeat.com/games/Skyward_Sword_HD.jpg',
    platform: 'Switch',
    runners: [{ name: 'lottie', channelUrl: '' }],
    badges: [],
    durationHours: 12,
    durationMinutes: 30,
    howLongToBeatId: '88306',
  },
  {
    gameProgressKey: 'links-awakening',
    title: "The Legend of Zelda: Link's Awakening",
    releaseYear: '2019',
    boxArt: 'https://howlongtobeat.com/games/Links_Awakening_Remake.jpg',
    platform: 'Switch',
    runners: [{ name: 'henry', channelUrl: '' }],
    badges: [],
    durationHours: 9,
    durationMinutes: 0,
    howLongToBeatId: '78782',
  },
];

export function Schedule() {
  const rows = useMemo(() => {
    let cursor = startDate.getTime();
    return games.map((game) => {
      const start = new Date(cursor);
      cursor +=
        game.durationHours * 60 * 60 * 1000 + game.durationMinutes * 60 * 1000;
      return { ...game, startDate: start };
    });
  }, []);

  const currentIndex = rows.findIndex((g) => g.gameProgressKey === currentGameKey);

  return (
    <div className="container p-3 min-vh-100 text-white text-center">
      <div className="my-3">
        <div className="mb-5">
          <h1 className="text-bloodmoon">Stream Schedule</h1>
          <p className="text-light mt-2">
            Check the dates and times below to see when (roughly) we will be playing
            your favourite titles so that you won't miss out!
          </p>
        </div>

        <div className="table-responsive">
          <table className="table bg-bloodmoon text-white" style={{ fontSize: 12 }}>
            <thead>
              <tr>
                <th scope="col">Day</th>
                <th scope="col">Time</th>
                <th scope="col">
                  <div className="d-none d-md-block">Console</div>
                </th>
                <th scope="col">Game</th>
                <th scope="col">
                  <div className="d-none d-md-block">Runner(s)</div>
                </th>
              </tr>
            </thead>
            <tbody>
              {rows.map((game, i) => {
                const played =
                  game.isCompleted || (currentIndex >= 0 && i < currentIndex);
                const playing = currentIndex === i;
                const rowClass = played
                  ? 'table-played'
                  : playing
                  ? 'table-currently-playing'
                  : '';
                return (
                  <tr key={game.gameProgressKey} className={rowClass}>
                    <td className="align-middle">
                      <div>{moment(game.startDate).format('ddd DD')}</div>
                      <div className="text-white-50">
                        {moment(game.startDate).format('MMM YYYY')}
                      </div>
                    </td>
                    <td className="align-middle">
                      <div>{moment(game.startDate).format('hh:mm')}</div>
                      <div className="text-white-50">
                        {moment(game.startDate).format('a')}
                      </div>
                    </td>
                    <td className="align-middle text-center">
                      <div className="d-none d-md-block">
                        <div className="badge rounded-pill bg-secondary p-2">
                          {game.platform}
                        </div>
                      </div>
                    </td>
                    <td className="align-middle">
                      <div className="d-flex justify-content-between align-items-center">
                        <div className="d-flex flex-column me-2">
                          <img
                            src={game.boxArt}
                            alt={`${game.title} Cover Art`}
                            title={`${game.title} Cover Art`}
                            style={{ maxWidth: 50 }}
                          />
                        </div>
                        <div className="text-center w-100">
                          <div>
                            {game.title} ({game.releaseYear})
                            {played && (
                              <div className="d-flex justify-content-center">
                                <div className="rounded-pill bg-dark mt-1 w-50">
                                  COMPLETED
                                </div>
                              </div>
                            )}
                            {playing && isLive && (
                              <div className="d-inline-block m-2">
                                <div
                                  className="badge bg-light text-dark fw-bold p-2 px-4"
                                  style={{ cursor: 'pointer' }}
                                  title="Watch Livestream"
                                >
                                  LIVE NOW!{' '}
                                  <span style={{ color: 'red' }}>
                                    <div className="d-inline-block live-circle ms-1" />
                                  </span>
                                </div>
                              </div>
                            )}
                          </div>
                          {game.badges.map((badge, b) =>
                            badge.url ? (
                              <span
                                key={b}
                                className={`badge m-1 ${badge.type}`}
                                title={badge.tooltip}
                              >
                                <a
                                  className="text-white"
                                  href={badge.url}
                                  target="_blank"
                                  rel="noreferrer"
                                >
                                  {badge.name}
                                </a>
                              </span>
                            ) : (
                              <span
                                key={b}
                                className={`badge m-1 ${badge.type}`}
                                title={badge.tooltip}
                              >
                                {badge.name}
                              </span>
                            ),
                          )}
                          <span className="badge m-2 bg-light">
                            <a
                              target="_blank"
                              rel="noreferrer"
                              className="text-dark"
                              title="How long to beat"
                              href={`https://howlongtobeat.com/game?id=${game.howLongToBeatId}`}
                            >
                              {game.durationHours}h {game.durationMinutes}m
                            </a>
                          </span>
                        </div>
                      </div>
                    </td>
                    <td className="align-middle text-center">
                      <div className="d-none d-md-block">
                        {game.runners.map((runner, r) =>
                          runner.channelUrl ? (
                            <a
                              key={r}
                              href={runner.channelUrl}
                              target="_blank"
                              rel="noreferrer"
                            >
                              <span className="badge rounded-pill bg-secondary p-2 m-1">
                                {runner.name}
                              </span>
                            </a>
                          ) : (
                            <span
                              key={r}
                              className="badge rounded-pill bg-secondary p-2 m-1"
                            >
                              {runner.name}
                            </span>
                          ),
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
