// src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  public isCollapsed = true;

  constructor() { }

  ngOnInit() {
  }

  donateFacebook() {
    window.open('https://www.facebook.com/donate/235288154058664/', '_blank');
  }

  donateJustGiving() {
    window.open('https://www.justgiving.com/fundraising/zeldathonuk-gameblast2019', '_blank');
  }

}

<nav class="navbar navbar-expand-lg">

  <a class="navbar-brand ms-3 me-4" routerLink="/" routerLinkActive="active-link">
    <img src="../../../assets/img/1gxaef91xpst0u.png" class="position-absolute"
         style="max-width: 32px; max-height: 32px; top: 8px; left: 115px; filter: opacity(0.75); transform: rotate(10deg);"
         title="GB Flag" alt="GB Flag">
    <img src="../../../assets/img/Zeldathon-Logo-WW-white.svg" style="min-width: 120px; max-height: 1.5em; filter: opacity(0.95);" title="ZeldathonUK" alt="ZeldathonUK">
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
          aria-controls="navbarToggleExternalContent" (click)="isCollapsed = !isCollapsed"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarToggleExternalContent" [ngbCollapse]="isCollapsed">
    <div class="d-flex flex-fill justify-content-around">

      <div class="d-flex flex-shrink-0 justify-content-center mx-2">
        <ul class="navbar-nav">
          <li class="nav-item nav-item-pink">
            <a class="nav-link nav-link-dark pb-0" routerLink="/" routerLinkActive="active-link">
              <div class="nav-icon-pink text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faHeart" transform="shrink-4" [styles]="{'margin-top': '-0.25em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                Home
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-orange">
            <a class="nav-link nav-link-dark pb-0" routerLink="/schedule" routerLinkActive="active-link">
              <div class="nav-icon-orange text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faListOl" transform="shrink-4" [styles]="{'margin-top': '-0.25em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                Schedule
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-gold">
            <a class="nav-link nav-link-dark pb-0" routerLink="/donations" routerLinkActive="active-link">
              <div class="nav-icon-gold text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faPoundSign" transform="shrink-7" [styles]="{'margin-top': '-0.45em'}"></fa-icon>
                  <fa-icon [icon]="faHandHolding" transform="shrink-4" [styles]="{'margin-top': '-0.25em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                Donations
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-green">
            <a class="nav-link nav-link-dark pb-0" routerLink="/incentives" routerLinkActive="active-link">
              <div class="nav-icon-green text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faCarrot" transform="shrink-4" [styles]="{'margin-top': '-0.25em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                Incentives
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-blue">
            <a class="nav-link nav-link-dark pb-0" routerLink="/charity" routerLinkActive="active-link">
              <div class="nav-icon-blue text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faGamepad" transform="shrink-4" [styles]="{'margin-top': '-0.05em'}"></fa-icon>
                  <fa-icon [icon]="faAccessibleIcon" transform="shrink-4" [styles]="{'margin-top': '-0.25em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                Charity
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-blurple">
            <a class="nav-link nav-link-dark pb-0" routerLink="/history" routerLinkActive="active-link">
              <div class="nav-icon-blurple text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faHistory" transform="shrink-4" [styles]="{'margin-top': '-0.25em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                History
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-purple">
            <a class="nav-link nav-link-dark pb-0" routerLink="/about" routerLinkActive="active-link">
              <div class="nav-icon-purple text-center" style="font-size: 2em;">
                <fa-layers>
                  <fa-icon [icon]="faCaretUp" transform="shrink-4" [styles]="{'margin-top': '-0.45em'}"></fa-icon>
                  <fa-icon [icon]="faCaretUp" transform="shrink-4" [styles]="{'margin-top': '-0.15em', 'margin-left': '0.45em'}"></fa-icon>
                  <fa-icon [icon]="faCaretUp" transform="shrink-4" [styles]="{'margin-top': '-0.15em', 'margin-right': '0.42em'}"></fa-icon>
                </fa-layers>
              </div>
              <div class="position-relative" style="margin-top: -1.1em;">
                About
              </div>
            </a>
          </li>
          <li class="nav-item nav-item-pink" *ngIf="this.user">
            <div class="nav-icon-pink text-center" style="font-size: 2em;">
              <fa-layers>
                <fa-icon [icon]="faChromecast" transform="shrink-4" [styles]="{'margin-top': '0.10em'}"></fa-icon>
              </fa-layers>
            </div>
            <div class="position-relative" style="margin-top: -1.1em;">
              <a class="nav-link nav-link-dark pb-0" routerLink="/obs" routerLinkActive="active-link">OBS</a>
            </div>
          </li>
        </ul>
      </div>

      <div class="d-flex flex-grow-1 justify-content-center">
        <div class="d-flex align-items-center me-3">
      <!--
          <app-combined-total></app-combined-total>
      -->
        </div>
      </div>

      <div class="d-flex flex-shrink-0 align-items-center">
        <ul class="navbar-nav">
          <li class="nav-item d-flex ms-2" [ngClass]="!isCollapsed ? 'p-1' : ''">
            <div class="align-self-center">
              <button class="btn btn-sm btn-facebook" (click)="donateFacebook();" style="font-family: 'Bungee', cursive;">
                <div class="d-flex" title="Donate via Facebook!">
                  <div class="d-flex align-self-center" style="width: .9em;">
                    <fa-icon [icon]="faFacebook" style="position: relative; top: 2px;"></fa-icon>
                  </div>
                  <span style="position: relative; top: 2px;">&nbsp;Donate</span>
                </div>
              </button>
            </div>
          </li>
          <li class="nav-item d-flex ms-2" [ngClass]="!isCollapsed ? 'p-1' : ''">
            <div class="align-self-center">
              <button class="btn btn-sm btn-justgiving" (click)="donateJustGiving();" style="font-family: 'Bungee', cursive;">
                <div class="d-flex" title="Donate via JustGiving!">
                  <div class="d-flex align-self-center" style="width: .9em;">
                    <img style="max-width: .9em; filter: brightness(10);"
                         src="../../../assets/img/justgiving-g.svg" alt="JustGiving logo">
                  </div>
                  <span style="position: relative; top: 1px;">&nbsp;Donate</span>
                </div>
              </button>
            </div>
          </li>
          <li class="nav-item d-flex mx-2" [ngClass]="!isCollapsed ? 'p-1' : ''" *ngIf="this.user">
            <div class="align-self-center">
              <button class="btn btn-sm btn-secondary" title="Logout" (click)="logout();">
                <fa-icon [icon]="faSignOutAlt"></fa-icon>
              </button>
            </div>
          </li>
        </ul>
      </div>

    </div>
  </div>

</nav>

// frontend/src/components/layout/Navbar.tsx
import { useState } from 'react';
import { NavLink, useNavigate } from 'react-router';
import { FontAwesomeIcon, FontAwesomeIconProps } from '@fortawesome/react-fontawesome';
import {
  faBars,
  faListOl,
  faPoundSign,
  faHandHolding,
  faCarrot,
  faGamepad,
  faHistory,
  faCaretUp,
} from '@fortawesome/free-solid-svg-icons';
import { faAccessibleIcon } from '@fortawesome/free-brands-svg-icons';
import { faHeart } from '@fortawesome/free-regular-svg-icons';
import { cn } from '@/lib/utils';
import { DonateButton } from '@/components/donations/DonateButton';
import { obsApi, usePolledQuery } from '@/lib/obsApi';
import './navbar.css';

const DEFAULT_LOGO = '/assets/img/Zeldathon-Logo-2026-Gold-Flash.svg';

type Glyph = FontAwesomeIconProps['icon'];

type NavItem = {
  to: string;
  label: string;
  layers: { icon: Glyph; style?: React.CSSProperties }[];
};

const navItems: NavItem[] = [
  { to: '/', label: 'Home', layers: [{ icon: faHeart, style: { marginTop: '-0.25em' } }] },
  {
    to: '/schedule',
    label: 'Schedule',
    layers: [{ icon: faListOl, style: { marginTop: '-0.25em' } }],
  },
  {
    to: '/donations',
    label: 'Donations',
    layers: [
      { icon: faPoundSign, style: { marginTop: '-0.45em', fontSize: '0.5em' } },
      { icon: faHandHolding, style: { marginTop: '-0.25em' } },
    ],
  },
  {
    to: '/incentives',
    label: 'Incentives',
    layers: [{ icon: faCarrot, style: { marginTop: '-0.25em' } }],
  },
  {
    to: '/charity',
    label: 'Charity',
    layers: [
      { icon: faGamepad, style: { marginTop: '-0.05em' } },
      { icon: faAccessibleIcon, style: { marginTop: '-0.25em' } },
    ],
  },
  {
    to: '/history',
    label: 'History',
    layers: [{ icon: faHistory, style: { marginTop: '-0.25em' } }],
  },
  {
    to: '/about',
    label: 'About',
    layers: [
      { icon: faCaretUp, style: { marginTop: '-0.45em' } },
      { icon: faCaretUp, style: { marginTop: '-0.15em', marginLeft: '0.45em' } },
      { icon: faCaretUp, style: { marginTop: '-0.15em', marginRight: '0.42em' } },
    ],
  },
];

export function Navbar() {
  const [collapsed, setCollapsed] = useState(true);
  const navigate = useNavigate();
  const { data: event } = usePolledQuery(obsApi.activeEvent, 10_000);
  const { data: theme } = usePolledQuery(obsApi.themeSettings, 60_000);
  const donationPages = event?.donation_pages ?? [];
  const logoSrc = theme?.logo_url || DEFAULT_LOGO;

  return (
    <nav className="navbar navbar-expand-lg">
      <NavLink
        to="/"
        className={({ isActive }) =>
          cn('navbar-brand ms-3 me-4', isActive && 'active-link')
        }
        onClick={() => navigate('/')}
      >
        <img
          src="/assets/img/1gxaef91xpst0u.png"
          className="position-absolute"
          style={{
            maxWidth: 32,
            maxHeight: 32,
            top: 8,
            left: 115,
            filter: 'opacity(0.75)',
            transform: 'rotate(10deg)',
          }}
          title="GB Flag"
          alt="GB Flag"
        />
        <img
          src={logoSrc}
          style={{ minWidth: 140, maxHeight: '2em', filter: 'opacity(0.95)' }}
          title="ZeldathonUK"
          alt="ZeldathonUK"
        />
      </NavLink>

      <button
        className="navbar-toggler border border-dark"
        type="button"
        aria-controls="navbarToggleExternalContent"
        aria-expanded={!collapsed}
        aria-label="Toggle navigation"
        onClick={() => setCollapsed((c) => !c)}
      >
        <span className="navbar-toggler-icon text-white">
          <FontAwesomeIcon icon={faBars} style={{ marginTop: '0.25em' }} />
        </span>
      </button>

      <div
        className={cn('collapse navbar-collapse', !collapsed && 'show')}
        id="navbarToggleExternalContent"
      >
        <div className="d-flex flex-fill justify-content-around">
          <div className="d-flex flex-shrink-0 justify-content-center mx-2">
            <ul className="navbar-nav">
              {navItems.map((item) => (
                <li key={item.to} className="nav-item nav-item-bloodmoon">
                  <NavLink
                    to={item.to}
                    end={item.to === '/'}
                    className={({ isActive }) =>
                      cn('nav-link nav-link-dark pb-0', isActive && 'active-link')
                    }
                  >
                    <div
                      className="nav-icon-bloodmoon text-center"
                      style={{ fontSize: '2em' }}
                    >
                      <span className="fa-layers">
                        {item.layers.map((layer, i) => (
                          <FontAwesomeIcon
                            key={i}
                            icon={layer.icon}
                            transform="shrink-4"
                            style={layer.style}
                          />
                        ))}
                      </span>
                    </div>
                    <div className="position-relative" style={{ marginTop: '-1.1em' }}>
                      {item.label}
                    </div>
                  </NavLink>
                </li>
              ))}
            </ul>
          </div>

          <div className="d-flex flex-grow-1 justify-content-center">
            <div className="d-flex align-items-center me-3" />
          </div>

          <div className="d-flex flex-shrink-0 align-items-center">
            {donationPages.length > 0 && (
              <div className={cn('me-3', !collapsed && 'p-1')}>
                <DonateButton
                  pages={donationPages}
                  currencySymbol={event?.currency_symbol}
                />
              </div>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
}
